apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticfarma
  labels:
    app: authenticfarma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authenticfarma
  template:
    metadata:
      labels:
        app: authenticfarma
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/authentic-prod-464216/authentic-repo/authenticfarma:IMAGE_TAG
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
