apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt ACME server URL for production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address for ACME registration
    email: admin@yo-coy.co  # Cambiar por tu email real
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: gce  # GKE default ingress class
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt ACME server URL for staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address for ACME registration
    email: admin@yo-coy.co  # Cambiar por tu email real
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: gce  # GKE default ingress class