apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentic-platform-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/desarrolloIngenios/authentic-platform.git' # <--- update to your repo
    targetRevision: main
    path: ci-cd/argo-apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
