apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yosoy-hc-backend-pvc
  namespace: yosoy-historia-clinica
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 5Gi