apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authenticfarma-candidatos
  namespace: argocd
  labels:
    app: authenticfarma-candidatos
    platform: authenticfarma
spec:
  project: default
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: dev  # Usar branch dev para desarrollo
    path: apps/authenticfarma/candidatos/Kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: authenticfarma-candidatos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3