apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isyours
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: main
    path: infra/manifests/isyours
  destination:
    server: https://kubernetes.default.svc
    namespace: isyours
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
