apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentic-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'REPO_URL' # replace with your git repo (git/ssh or https)
    targetRevision: main
    path: infra/k8s-manifests/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
