apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authenticfarma-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: authenticfarma
    app.kubernetes.io/part-of: authentic-platform
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/desarrolloIngenios/authentic-platform.git
    targetRevision: main
    path: infra/k8s-manifests/apps/authenticfarma
  destination:
    server: https://kubernetes.default.svc
    namespace: authenticfarma
  syncPolicy:
    # Manual sync para producción
    syncOptions:
    - CreateNamespace=true