apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME-placeholder
  labels:
    app: APP_NAME-placeholder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: APP_NAME-placeholder
  template:
    metadata:
      labels:
        app: APP_NAME-placeholder
    spec:
      containers:
      - name: app
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:IMAGE_TAG
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: APP_NAME-config
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
