apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: authentic-candidatos-backendconfig
  namespace: authenticfarma
spec:
  timeoutSec: 300 
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 60
    healthyThreshold: 1
    unhealthyThreshold: 10
    type: HTTP
    requestPath: /healthz
    port: 80