apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentic-candidatos
  namespace: authenticfarma
  labels:
    app: authentic-candidatos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentic-candidatos
  template:
    metadata:
      labels:
        app: authentic-candidatos
      annotations:
        iam.gke.io/gcp-service-account: authentic-candidatos-gsa@authentic-prod-464216.iam.gserviceaccount.com
    spec:
      serviceAccountName: authentic-candidatos-ksa
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          command:
            - "/cloud-sql-proxy"
          args:
            - "--private-ip"
            - "--address=0.0.0.0"
            - "--port=3306"
            - "authenticfarma-425820:us-central1:authentic"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          - name: queue-worker
          image: us-central1-docker.pkg.dev/authentic-prod-464216/authenticfarma-repo/authentic-candidatos:v4.1.0
          command: ["php", "artisan", "queue:work"]
          envFrom:
            - secretRef:
                name: authentic-candidatos-secret
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_DATABASE
              value: "authentic"
            - name: DB_USERNAME
              value: "candidatosuser"
            - name: CACHE_DRIVER
              value: "database"
            - name: QUEUE_CONNECTION
              value: "database"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
        - name: authentic-candidatos
          image: us-central1-docker.pkg.dev/authentic-prod-464216/authenticfarma-repo/authentic-candidatos:v4.1.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 36
          envFrom:
            - secretRef:
                name: authentic-candidatos-secret
          env:
            - name: APP_NAME
              value: "Authentic-candidatos"
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
            - name: APP_URL
              value: "https://candidatos.authenticfarma.com"
            - name: LOG_CHANNEL
              value: "stack"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "authentic"
            - name: DB_USERNAME
              value: "candidatosuser"
            - name: BROADCAST_DRIVER
              value: "log"
            - name: CACHE_DRIVER
              value: "database"
            - name: QUEUE_CONNECTION
              value: "database"
            - name: SESSION_DRIVER
              value: "database"
            - name: SESSION_LIFETIME
              value: "120"
            - name: SESSION_DOMAIN
              value: ".authenticfarma.com"
            - name: SESSION_COOKIE
              value: "authentic_session"
            - name: SESSION_SECURE_COOKIE
              value: "true"
            - name: SESSION_SAME_SITE
              value: "none"
            - name: MAIL_MAILER
              value: "smtp"
            - name: MAIL_HOST
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USERNAME
              value: "stack.dev@authentic.com.co"
            - name: MAIL_ENCRYPTION
              value: "tls"
            - name: MAIL_FROM_ADDRESS
              value: "activacion@authenticfarma.com"
            - name: MAIL_FROM_NAME
              value: "Authentic Farma"
            - name: GOOGLE_CLOUD_PROJECT_ID
              value: "authentic-prod-464216"
            - name: GOOGLE_CLOUD_STORAGE_BUCKET
              value: "backups-prod"
            - name: GOOGLE_CLOUD_STORAGE_PATH_PREFIX
              value: "null"
            - name: GOOGLE_CLOUD_STORAGE_API_URI
              value: "null"
            - name: GOOGLE_CLOUD_KEY_FILE
              value: "keys/gcs-key.json"
            - name: PUSHER_APP_ID
              value: ""
            - name: PUSHER_APP_KEY
              value: ""
            - name: PUSHER_APP_SECRET
              value: ""
            - name: PUSHER_APP_CLUSTER
              value: "mt1"
            - name: GOOGLE_CLIENT_ID
              value: "1087239389819-5eck0eo7e3o5f1nku8gumb0mitgl6ag5.apps.googleusercontent.com"
            - name: GOOGLE_REDIRECT
              value: "https://candidatos.authenticfarma.com/google-auth/callback"