apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authentic-candidatos-hpa
  namespace: authenticfarma
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentic-candidatos
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70