apiVersion: v1
kind: Service
metadata:
  name: authentic-candidatos-service
  namespace: authenticfarma
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  
    cloud.google.com/backend-config: '{"default": "authentic-candidatos-backendconfig"}'
spec:
  type: ClusterIP   
  selector:
    app: authentic-candidatos
  ports:
    - name: http
      port: 80        
      targetPort: 80  
