# GitLab CI pipeline template for building Laravel images and updating GitOps repo
stages:
  - test
  - build
  - publish
  - update-manifests

variables:
  PROJECT_ID: "PROJECT_ID"          # replace
  REGION: "us-central1"            # replace
  REPOSITORY: "laravel-app"        # replace per app
  IMAGE: "app-image"               # replace per app

before_script:
  - echo "Running pipeline for $CI_PROJECT_PATH"

test_job:
  stage: test
  image: php:8.2
  script:
    - apt-get update -y && apt-get install -y unzip git zip
    - curl -sS https://getcomposer.org/installer | php -- && php composer.phar install --no-interaction --prefer-dist
    - ./vendor/bin/phpunit || echo "Tests executed (failing tests will fail pipeline if desired)"

build_job:
  stage: build
  image: docker:24-dind
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$CI_COMMIT_SHORT_SHA .
    - echo "Built image $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$CI_COMMIT_SHORT_SHA"

publish_job:
  stage: publish
  image: google/cloud-sdk:slim
  script:
    - echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp_key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcp_key.json
    - gcloud auth configure-docker $REGION-docker.pkg.dev -q
    - docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main

update_manifests:
  stage: update-manifests
  image: alpine/git
  script:
    - git clone $GITOPS_REPO_URL gitops
    - cd gitops/infra/k8s-manifests/apps/APP_NAME
    - sed -i "s/IMAGE_TAG/$CI_COMMIT_SHORT_SHA/g" deployment.yaml
    - git add deployment.yaml && git commit -m "ci: update image APP_NAME to $CI_COMMIT_SHORT_SHA" || echo "no changes"
    - git push origin main
  only:
    - main
