# ArgoCD Server Configuration for HTTPS
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "false"
  server.enable.proxy.extension: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-server-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server-config
    app.kubernetes.io/part-of: argocd
data:
  url: "https://argo.authenticfarma.com"
  application.instanceLabelKey: argocd.argoproj.io/instance
  oidc.config: |
    name: OIDC
    issuer: https://argo.authenticfarma.com/api/dex
    clientId: argo-server
    clientSecret: $oidc.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  # Allow insecure connections for development
  tls.config: |
    certs:
      argo.authenticfarma.com: |
        -----BEGIN CERTIFICATE-----
        # Certificate will be automatically generated by cert-manager
        -----END CERTIFICATE-----